#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync, copyFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const skillRoot = dirname(here);
const defaultTemplate = join(skillRoot, "assets", "templates", "skill");
const examplesDir = join(skillRoot, "assets", "examples");

function parseArgs(argv) {
  const args = {};
  for (let i = 2; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--input") args.input = argv[++i];
    else if (arg === "--output") args.output = argv[++i];
    else if (arg === "--template") args.template = argv[++i];
    else if (arg === "--init-config") args.initConfig = argv[++i];
    else if (arg === "--help") args.help = true;
    else throw new Error(`Unknown argument: ${arg}`);
  }
  return args;
}

function usage() {
  console.log(`Usage:
  node scripts/render-skill.mjs --input config.json --output <skill-dir> [--template <dir>]
  node scripts/render-skill.mjs --init-config functional`);
}

function slugify(value) {
  return String(value || "ai-skill")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 63) || "ai-skill";
}

function listFiles(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) listFiles(full, out);
    else out.push(full);
  }
  return out;
}

function valueFor(config, key) {
  const skillName = slugify(config.skillName || config.displayName || "ai-skill");
  const defaults = {
    skillName,
    displayName: config.displayName || skillName.split("-").map((part) => part[0]?.toUpperCase() + part.slice(1)).join(" "),
    skillDescription: config.skillDescription || "Reusable AI skill generated by AI Skill Maker.",
    shortDescription: config.shortDescription || `Use ${config.displayName || skillName}`,
    defaultTask: config.defaultTask || "complete the requested workflow",
    skillPurpose: "- inferred_assumption: Skill purpose should be confirmed with the maintainer.",
    capability: "- inferred_assumption: Capability should be confirmed with concrete examples.",
    usersAndTriggers: "- inferred_assumption: Triggering user requests should be confirmed.",
    inputsAndOutputs: "- inferred_assumption: Inputs and outputs should be confirmed.",
    boundaries: "- recommended_standard: Confirm before destructive, externally visible, private-data, or credential-sensitive operations.",
    workflow: "1. Clarify the request.\n2. Inspect relevant inputs.\n3. Use bundled references, assets, or scripts when applicable.\n4. Verify the output.\n5. Summarize results and assumptions.",
    resources: "- inferred_assumption: Add references, assets, and scripts as the skill matures.",
    verification: "- inferred_assumption: Verification should be made concrete for this skill.",
    standardFlow: "- inferred_assumption: Standard workflow should be confirmed.",
    edgeCases: "- inferred_assumption: Edge cases should be collected during forward tests.",
    failureHandling: "- recommended_standard: Report failing commands, partial outputs, and next recovery steps.",
    referenceResources: "- inferred_assumption: No durable references have been declared yet.",
    assetResources: "- inferred_assumption: No reusable assets have been declared yet.",
    scriptResources: "- inferred_assumption: No deterministic scripts have been declared yet.",
    automatedChecks: "- inferred_assumption: Automated checks have not been configured yet.",
    manualQa: "- inferred_assumption: Manual QA should be confirmed for user-facing artifacts.",
    forwardTests: "- recommended_standard: Add realistic forward-test prompts for this skill.",
    generatedOutputs: "- inferred_assumption: Generated outputs should be listed once file formats are selected.",
    editRestrictions: "- recommended_standard: Avoid overwriting user-provided source files unless explicitly requested.",
    evidenceLedger: "- inferred_assumption: Evidence ledger should be refreshed from observed facts and declared intent.",
  };
  const value = config[key] ?? defaults[key] ?? "";
  return Array.isArray(value) ? value.join("\n") : String(value);
}

function render(text, config) {
  return text.replace(/\{\{([a-zA-Z0-9_]+)\}\}/g, (_, key) => valueFor(config, key));
}

function manualBlock(text) {
  const match = text.match(/<!-- BEGIN USER RULES -->([\s\S]*?)<!-- END USER RULES -->/);
  return match ? match[1] : null;
}

function preserveManualBlock(next, previous) {
  const block = manualBlock(previous);
  if (block === null) return next;
  return next.replace(/<!-- BEGIN USER RULES -->[\s\S]*?<!-- END USER RULES -->/, `<!-- BEGIN USER RULES -->${block}<!-- END USER RULES -->`);
}

const args = parseArgs(process.argv);
if (args.initConfig) {
  const mode = String(args.initConfig).toLowerCase();
  if (!["functional"].includes(mode)) {
    console.error("--init-config must be one of: functional");
    process.exit(1);
  }
  console.log(readFileSync(join(examplesDir, "functional-skill-config.json"), "utf8"));
  process.exit(0);
}

if (args.help || !args.input || !args.output) {
  usage();
  process.exit(args.help ? 0 : 1);
}

const config = JSON.parse(readFileSync(args.input, "utf8"));
config.skillName = slugify(config.skillName || config.displayName || "ai-skill");
const template = args.template || defaultTemplate;
mkdirSync(args.output, { recursive: true });

for (const source of listFiles(template)) {
  const rel = relative(template, source);
  const dest = join(args.output, rel);
  mkdirSync(dirname(dest), { recursive: true });
  const raw = readFileSync(source);
  if (/\.(md|yaml|yml|mjs|json|txt)$/.test(source)) {
    let text = render(raw.toString("utf8"), config);
    if (existsSync(dest) && text.includes("BEGIN USER RULES")) {
      text = preserveManualBlock(text, readFileSync(dest, "utf8"));
    }
    writeFileSync(dest, text);
  } else {
    copyFileSync(source, dest);
  }
}

console.log(`Rendered ${config.skillName} to ${args.output}`);
